### ISSUE TITLE
Impressum

### ISSUE THREAD

**Issue by luechtdiode** [MrCode97/windowOrganizer#1]
Add an impressum site with all relevant legal notices (see https://habefast.ch/en/legal-notices-on-a-website-in-switzerland/)

**Comment by luechtdiode** [comment]
Specify the responsibility of a calendar creator for all content (text, images) in his calendar.

**Some detailed suggestions**
- Checkbox with the text that the _creator of the calendar_ is responsible for ensuring that no unlawful content such as sexist, racist, religious or offensive comments or images are uploaded to their calendar. They must actively monitor the uploaded content and remove problematic content.
- Checkbox for _people who upload a comment or image_ with the text that no problematic content will be tolerated (if necessary deleted) and that the person must have the rights to the image.

**Comment by MrCode97** [comment]
Please populate the respective values (Company Name, .., Contact Mail, ..,  Privacy Policy Link) in `ImpressumPage.js` and make a pull request.

Feel free to modify the `ImpressumPage.js` as desired.
