### ISSUE TITLE
Make uploaded Images deletable

### ISSUE THREAD

**Issue by luechtdiode** [MrCode97/windowOrganizer#2]
- Problematic content should be deletable from the calendar-owner's account.
- Unwanted uploads of window content-suppliers: They should be able to delete all of theirs uploaded content (text and images)

**Comment by MrCode97** [comment]
- Authors of comments, images can delete their content (as long as calendar not locked)
![image](https://github.com/user-attachments/assets/66e43a77-3019-4075-b6d7-a9cdd3aef115)

- Calendar Owners can delete any content within their calendars (as long as not locked)
![image](https://github.com/user-attachments/assets/3dbc70e0-b35a-4122-bb02-124f00eaeb7c)

- Calendar Owners can lock / unlock calendars, basically 'freezing' a state. The intention for the 'lock' feature, is to relive a calendar owner from continuously having to monitoring the content.
![image](https://github.com/user-attachments/assets/28639fd6-e3dc-4442-a282-371d61dbff91)

**Comment by luechtdiode** [comment]
There is an issue with some kind of images, that are not shown in the gallery after uploading. So they can't be removed there.
