### ISSUE TITLE
German text version

### ISSUE THREAD

**Issue by MrCode97** [MrCode97/windowOrganizer#20]

**Comment by MrCode97** [comment]
Most functionality is there, still to fix is:
- German version of Impressum results in:`react__WEBPACK_IMPORTED_MODULE_0__.useContext(...).public.assets is undefined`
- In App.js, the text-injection works but switching the language only effects sub-components - not the text in `App.js`.

Things to check:
- Are the files `de-DE.json`, `en-US.json` in the right path `public/lang/` and is the `default.json` not interfering ?
- I think we could either 
  - make the text-injected constants variable, i.e. `let` and reload / overwrite with new language, or 
  - trigger a re-render of the whole page `App.js`. In that case, need to make sure that the default-logic does not overwrite the language-switch if we reload. 
 
I.e. I started this:
```js
//App.js
const locale = navigator.language;
let defaultlang;
if(localStorage.getItem('lang')) {
  defaultlang = localStorage.getItem('lang');
} else if (locale.startsWith("de")) {
  defaultlang = "de-DE";
} else {
  defaultlang = "en-US";
}
```
so we could read/set the `lang` in localStorage, if a user makes an intend language change. Note, only if nothing is set, we consider `navigator.language`.


@luechtdiode if you have the time and energy, I'd appreciate you working this out. As you already introduced this text-injection within the Impressum, I think you'll get there faster. Otherwise I'll fix it later.

**Comment by luechtdiode** [comment]
- undefined public.assets issue is solved
- The lang-files are back in the build distro. Only the text-variables are serverd from the static content and can be replaced for each environment/deployment.
- translations in App.js: I'll extract sidebar components to get support for lang-changes

**Comment by luechtdiode** [comment]
current state is deployed for review at test.advents-calendar.org

**Comment by MrCode97** [comment]
See: b8c8066586d682e19acc0fb81b065c2d75d532e7
- refactored App into Toolbar and Navigationbar
- fixed missing translation in Tool- & Navigationbar
- added an alternative language-switch, see: 
  - `frontend/src/components/LangBadge.tsx`
  - `frontend/src/components/LangFlag.tsx`
- added an alternative place for the language-switch, compare:
  - `frontend/src/components/NavigationBar.tsx:106`
  - `frontend/src/components/AdventToolbar.tsx:58`
- fixed a missing hint in `frontend/src/components/UserRegistrationForm.js`

Prefer the `LangFlag`-switch and position `AdventToolbar.tsx:58`, but let me know you think?

Regarding warnings:
- `src/App.js  Line 66:27:  'setShowMyCalendars' is assigned a value but never used  no-unused-vars` 
Contrary to the warning, used in both `NavigationBar` and `AdventToolbar` (but not in `App.js` - result of factoring)
- the other warnings are related to `LangBadge`, `LangFlag` imports - as soon as we decided on a switch and position, I'll remove the unused imports and they should go away.

**Comment by luechtdiode** [comment]
current state is deployed for review at test.advents-calendar.org
cool: 
![grafik](https://github.com/user-attachments/assets/488a2f39-5b30-4546-b93c-eb3e449b3bd0)
