### ISSUE TITLE
Make it possible for a user to clear his calendar window reservation

### ISSUE THREAD

**Issue by luechtdiode** [MrCode97/windowOrganizer#3]
If a user joined the calender with one or more windows (dates), he should also be able to give some windows (dates) back.

**Comment by MrCode97** [comment]
Ability to delete / de-register a window added:
![image](https://github.com/user-attachments/assets/13fef973-1b6b-486b-b257-fd18376a8437)

Ability to delete a calendar added:
![image](https://github.com/user-attachments/assets/bc239b72-b2f8-4d04-bf0c-e8e0a459dc7a)

**Comment by luechtdiode** [comment]
cool!
